name: Netlify Deploy
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jsmrcaga/action-netlify-deploy@v2.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_DEPLOY_TO_PROD: true
